---
- name: Converge
  hosts: all
  vars:
    syslog_udp_enable: false
    syslog_udp_address: 127.0.0.1
    syslog_udp_port: 514
    syslog_tcp_enable: false
    syslog_tcp_port: 514

  pre_tasks:
    - name: Install Dependencies.
      yum: name=libselinux-python
      when: ansible_os_family == 'RedHat'
      changed_when: false

  roles:
    - role: ansible-role-syslog
